DOMAIN = "egdpowerdata"
CONF_CLIENT_ID = "client_id"
CONF_CLIENT_SECRET = "client_secret"
CONF_EAN = "ean"
BASE_URL = "https://data.distribuce24.cz"
TOKEN_URL = "https://idm.distribuce24.cz/oauth/token"
DATA_URL = BASE_URL + "/rest/spotreby"
